### ISSUE TITLE
How to set predefined sources

### ISSUE THREAD

**Issue by n-peugnet** [JodliDev/calendar#1]
Hello,

Thank you very much for this new fork.
I almost succeeded to make this plugin work as I wanted, despite the few problems I had with the Postgres SQL script (I will probably send you some fixes soon), but I did not find how to set a predefined source for all users, based on their username and password.

For reference, here is how it was made in fasterit's fork:
https://github.com/fasterit/roundcube_calendar/blob/d1278c141ef73030de002342c15f65439ffd74e9/calendar/config.inc.php.dist#L182-L188

texxasrulez's one added a `auth_type` parameter:
https://github.com/texxasrulez/calendar/blob/385b3ee969b68cb879ebb3a78f9b49eea7cf9bb6/config.inc.php.dist#L236

**Comment by JodliDev** [comment]
If I remember correcty, I ditched the code that would add preinstalled calendars.
In the faster-it source, it was done as a compromise to be able to add calendars altogether (since the GUI did not give you any option of doing so). But it was only implemented for calldav, meaning that "calendar_preinstalled_calendars" was ignored for other drivers. So adding it properly, would mean that the other drivers would have to be changed as well.

But my main reason was, that it created a lot of problems, since it would try and add these calendars everytime you connect ANY calendar source even if you dont want to.

I would suggest having preinstalled calendars at your actual caldav provider. It feels a bit dirty having something "preinstalled" in a plugin that only serves as a frontend for an already existing source :)
