### ISSUE TITLE
[installation] MySQL requests do not use table prefix

### ISSUE THREAD

**Issue by gqdc** [JodliDev/calendar#33]
Hi,

I follow the installation instructions, but, it fails when runing `plugins/calendar/drivers/database/SQL/mysql.initial.sql` with the message : 

```
Creating database schema... ERROR: [1146] Table 'roundcube_dev.system' doesn't exist (SQL Query: REPLACE INTO system (name, value) VALUES ('calendar-database-version', '2015022700'))
[FAILED]
ERROR: [1146] Table 'roundcube_dev.system' doesn't exist
```

Indeed, all my roundcube's tables has a prefix.
So the correct request must be : 

`REPLACE INTO **prefix_**system (name, value) VALUES ('calendar-database-version', '2015022700'))`

EDIT : All the other resquests in `plugins/calendar/drivers/database/SQL/mysql.initial.sql` and `plugins/calendar/drivers/caldav/SQL/mysql.initial.sql` are wrong.

**Comment by gqdc** [comment]
I manually edited the requests with my table prefix, and everything went well.

**Comment by matikij** [comment]
The proper fix here is to not use REPLACE INTO but to use INSERT INTO. REPLACE INTO is not recognized by [roundcube's rcutil::fix_table_names](https://github.com/roundcube/roundcubemail/blob/d9d51b8d9c8bdab60c2b994bd06d75a3e75f2767/program/lib/Roundcube/rcube_db.php#L1433) and thus the prefix is not added. Since this is the initial configuration REPLACE INTO should behave as INSERT INTO anyway.
